filebeat.registry.path: /usr/share/filebeat/data/registry

filebeat.modules:
  - module: logstash


# output.elasticsearch:
#   hosts: ["localhost:5044"]
  # index: "filebeat-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kb01:5601"

output.logstash:
  hosts: ["ls01:5044"]
  # indices:
  #   - index: "%{+yyyy:MM.dd}"  
  
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.name: rng
          config:
            - type: log
              containers.ids:
                - '${data.docker.container.id}'
              paths:
                - '/var/lib/docker/containers/${data.docker.container.id}/*.log'

# Template name. By default the template name is "filebeat-%{[agent.version]}"
# The template name and pattern has to be set in case the Elasticsearch index pattern is modified.
setup.template.name: "filebeat"

# Template pattern. By default the template pattern is "-%{[agent.version]}-*" to apply to the default index settings.
# The first part is the version of the beat and then -* is used to match all daily indices.
# The template name and pattern has to be set in case the Elasticsearch index pattern is modified.
setup.template.pattern: "filebeat-*"
              
# processors:
#   - decode_json_fields:
#       fields: ["message"]
#       process_array: true
#       max_depth: 10
#       target: "log"
#       overwrite_keys: true
