filebeat.registry.path: /usr/share/filebeat/data/registry

output.logstash:
  hosts: ["0.0.0.0:5044"]
  indices:
    - index: "%{+YYYY:MM.dd}"  
  
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              - equals: 
                  docker.container.name: rng
          config:
            - type: log
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`('|_]"]
              
processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: true
      max_depth: 10
      target: "log"
      overwrite_keys: true
