filebeat.modules:
  - module: elasticsearch
    server:
      enabled: true

  - module: logstash
    log:
      enabled: true

      paths:
      - /var/log/*.log

filebeat.inputs:
  - type: log
      paths:
        - /var/log/*.log
  - type: stdin
  - type: container

    # Paths for container logs that should be crawled and fetched.
    paths:
      - /var/lib/docker/containers/*/*.log

    # Configure stream to filter to a specific stream: stdout, stderr or all (default)
    stream: all
  # prospectors:
  #   - paths:
  #     - /var/lib/docker/containers/*/*.log
  #     input_type: log

  #   -type: stdin


  # Change to true to enable this input configuration.
  enabled: true
  reload.enabled: true
  reload.period: 10s

output.logstash:
  hosts: ["0.0.0.0:5044"]  
  loadbalance: true
  index: filebeat

logging.level: info

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: '*'
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              # exclude_lines: ["^\\s+[\\-`('.|_]"] 
    