filebeat.modules:
- module: elasticsearch
  server:
    enabled: true

- module: logstash
  log:
    enabled: true

filebeat.inputs:
- type: docker
  containers.ids: '*'

output.logstash:
  hosts: ["0.0.0.0:5044"]

logging.level: info
    