version: '3.2'
services:
  # prometheus:
  #   build: 
  #     context: ./dockerfiles
  #     dockerfile: Dockerfile-prometheus
  #   container_name: prometheus
  #   ports:
  #   - 9090:9090
  #   command:
  #   - --config.file=/etc/prometheus/prometheus.yml
  #   volumes:
  #   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   depends_on:
  #   - cadvisor

  # cadvisor:
  #   image: gcr.io/google-containers/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #   - 8080:8080
  #   volumes:
  #   - /:/rootfs:ro
  #   - /var/run:/var/run:rw
  #   - /sys:/sys:ro
  #   - /var/lib/docker/:/var/lib/docker:ro
  #   depends_on:
  #   - redis

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #   - 6379:6379

  # number_gen:
  #   build: 
  #     context: .
  #     dockerfile: ./dockerfiles/Dockerfile-rand_num_gen

  elasticsearch:
    build: 
      context: ./dockerfiles
      dockerfile: Dockerfile-elasticsearch
    container_name: es01
    environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
    volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
  
  logstash:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile-logstash
    container_name: ls01
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - elastic
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    build: 
      context: ./dockerfiles
      dockerfile: Dockerfile-kibana
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elastic

  filebeat:
    container_name: fb01
    user: root
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile-filebeat
    restart: "no"
    command: "filebeat -e -d *"
    volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:rw
        - ./filebeat/files/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elastic
    links:
      - "logstash:logstash"
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:

networks:
  elastic:
