#global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s
  #query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'
# Scrape configs only contain one scrape target
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080