FROM python:3.9-slim-buster

# RUN apt-get update -y && \
    # apt-get install -y python3-pip

WORKDIR /app

COPY . .

# COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]