FROM docker.elastic.co/logstash/logstash:7.15.0
# COPY logstash/logstash.yml /usr/share/logstash/config/logstash.yml
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
ADD logstash/pipeline/ /usr/share/logstash/pipeline/
ADD logstash/config/ /usr/share/logstash/config/